# NumPy - Ayuda Memoria
**Formato:** qué quiero hacer → código → resultado.

Secciones:
1. Estructuras de datos
2. Eficiencia computacional
3. Lógica de selección
4. Tratamiento de datos

In [1]:
import numpy as np

---
## 1. Estructuras de Datos

### 1.1 Creación de arrays

In [50]:
# Desde una lista
a = np.array([1, 2, 3])
print(a)
a = np.array([1, 2, 3], dtype=float)
print(a)
# Desde una lista de listas
b = np.array([[1, 2], [3, 4]])
print(b)
# Desde un rango
c = np.arange(0, 10, 2)
print(c)
# Desde una función
d = np.linspace(0, 1, 5)
print(d)    
# Desde un archivo
# e = np.loadtxt('data.txt')    


[1 2 3]
[1. 2. 3.]
[[1 2]
 [3 4]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [3]:
# Matriz de ceros 2x3
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Matriz de unos 3x2
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
# Rellenar con un valor fijo
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [6]:
# Rango de números (inicio, fin, paso)
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [7]:
# Matriz identidad 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# Aleatorios enteros entre 0 y 10, forma 2x3
np.random.randint(0, 10, (2, 3))

array([[7, 0, 3],
       [3, 2, 3]], dtype=int32)

In [9]:
# Aleatorios decimales (0 a 1)
np.random.rand(5)

array([0.71029844, 0.81535477, 0.31732059, 0.57626716, 0.1637946 ])

### 1.2 Atributos del array

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("shape  :", arr.shape)   # forma (filas, cols)
print("dtype  :", arr.dtype)   # tipo de dato
print("ndim   :", arr.ndim)    # cantidad de dimensiones
print("size   :", arr.size)    # total de elementos
print("nbytes :", arr.nbytes)  # bytes en memoria

shape  : (2, 3)
dtype  : int64
ndim   : 2
size   : 6
nbytes : 48


In [11]:
# Cambiar el tipo de dato
arr_int = arr.astype(np.int32)
print(arr_int.dtype)

int32


### 1.3 Reshape (cambiar forma)

In [12]:
# De 1D a 2D
v = np.arange(1, 7)
print("original:", v)
print("reshape 2x3:\n", v.reshape(2, 3))

original: [1 2 3 4 5 6]
reshape 2x3:
 [[1 2 3]
 [4 5 6]]


In [13]:
# Usar -1 para que NumPy calcule la dimensión que falta
v.reshape(-1, 2)   # 6 elementos / 2 cols = 3 filas

array([[1, 2],
       [3, 4],
       [5, 6]])

### 1.4 Aplanar: ravel vs flatten

In [14]:
M = np.array([[1, 2], [3, 4]])

# ravel → vista (modificarlo afecta el original)
r = M.ravel()
r[0] = 99
print("M después de modificar ravel:\n", M)

M después de modificar ravel:
 [[99  2]
 [ 3  4]]


In [15]:
# flatten → copia (no afecta el original)
M = np.array([[1, 2], [3, 4]])
f = M.flatten()
f[0] = 99
print("M después de modificar flatten:\n", M)

M después de modificar flatten:
 [[1 2]
 [3 4]]


### 1.5 Transposición (intercambiar filas y columnas)

In [16]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A (2x3):\n", A)
print("A.T (3x2):\n", A.T)

A (2x3):
 [[1 2 3]
 [4 5 6]]
A.T (3x2):
 [[1 4]
 [2 5]
 [3 6]]


### 1.6 Concatenación (unir arrays)

In [17]:
X1 = np.array([[1, 2], [3, 4]])
X2 = np.array([[5, 6], [7, 8]])

# vstack → apila vertical (más filas / más muestras)
print("vstack:\n", np.vstack([X1, X2]))

vstack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [18]:
# hstack → apila horizontal (más columnas / más features)
print("hstack:\n", np.hstack([X1, X2]))

hstack:
 [[1 2 5 6]
 [3 4 7 8]]


In [19]:
# concatenate → genérico, especificás axis
print("concatenate axis=0:\n", np.concatenate([X1, X2], axis=0))
print("concatenate axis=1:\n", np.concatenate([X1, X2], axis=1))

concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


---
## 2. Eficiencia Computacional

### 2.1 Lista vs NumPy: memoria

In [20]:
import sys

lista = list(range(1_000_000))
array = np.arange(1_000_000)

mem_lista = sys.getsizeof(lista) + sum(sys.getsizeof(x) for x in lista)
mem_array = array.nbytes

print(f"Lista : {mem_lista/1024/1024:.2f} MB")
print(f"NumPy : {mem_array/1024/1024:.2f} MB")
print(f"NumPy es ~{mem_lista/mem_array:.0f}x más eficiente")

Lista : 34.33 MB
NumPy : 7.63 MB
NumPy es ~5x más eficiente


### 2.2 Lista vs NumPy: velocidad

In [21]:
import time

lista = list(range(10_000_000))
array = np.arange(10_000_000)

t = time.time()
sum(lista)
print(f"Lista: {time.time()-t:.4f} s")

t = time.time()
array.sum()
print(f"NumPy: {time.time()-t:.4f} s")

Lista: 0.5240 s
NumPy: 0.0810 s


### 2.3 Vectorización (operar sin bucles)

In [22]:
# Operación con escalar
salarios = np.array([100, 200, 300, 400])
salarios * 1.10   # aumento del 10% a todos

array([110., 220., 330., 440.])

In [23]:
# Operación entre arrays (elemento a elemento)
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("suma:", a + b)
print("mult:", a * b)

suma: [11 22 33]
mult: [10 40 90]


### 2.4 Broadcasting (formas distintas)

In [24]:
# Restar la media de cada columna a una matriz
X = np.array([[1, 2, 3], [4, 5, 6]])
medias = X.mean(axis=0)   # shape (3,)
print("medias:", medias)
print("X - medias:\n", X - medias)   # NumPy expande medias a (2,3)

medias: [2.5 3.5 4.5]
X - medias:
 [[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]


In [25]:
# Cuidado: broadcasting inesperado
a = np.array([1, 2, 3])         # shape (3,)
b = np.array([[1], [2], [3]])   # shape (3,1)
result = a + b                  # ¡da matriz 3x3, no vector!
print(result)
print("shape:", result.shape)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
shape: (3, 3)


---
## 3. Lógica de Selección

### 3.1 Indexación básica

In [26]:
# 1D
v = np.array([10, 20, 30, 40, 50])
print("primero :", v[0])
print("último  :", v[-1])

primero : 10
último  : 50


In [27]:
# 2D: [fila, columna]
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("M[0,1]:", M[0, 1])   # fila 0, col 1
print("M[2,2]:", M[2, 2])   # esquina inferior derecha

M[0,1]: 2
M[2,2]: 9


### 3.2 Slicing (rangos)

In [28]:
v = np.arange(10)
print("v[2:6]  :", v[2:6])     # del 2 al 5
print("v[::2]  :", v[::2])     # cada 2 elementos
print("v[::-1] :", v[::-1])    # invertir

v[2:6]  : [2 3 4 5]
v[::2]  : [0 2 4 6 8]
v[::-1] : [9 8 7 6 5 4 3 2 1 0]


In [29]:
# Slicing 2D
M = np.arange(1, 26).reshape(5, 5)
print("matriz:\n", M)
print("\nfila 2 completa:", M[2, :])
print("\núltimas 2 columnas:\n", M[:, -2:])
print("\nsubmatriz central 3x3:\n", M[1:4, 1:4])

matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

fila 2 completa: [11 12 13 14 15]

últimas 2 columnas:
 [[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]

submatriz central 3x3:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


### 3.3 Vista vs Copia ⚠️

In [30]:
# Slicing devuelve VISTA → modificar afecta al original
M = np.array([[1, 2, 3], [4, 5, 6]])
vista = M[0:1, 0:2]
vista[0, 0] = 999
print("M (modificado!):\n", M)

M (modificado!):
 [[999   2   3]
 [  4   5   6]]


In [31]:
# Si querés independencia, usá .copy()
M = np.array([[1, 2, 3], [4, 5, 6]])
copia = M[0:1, 0:2].copy()
copia[0, 0] = 999
print("M (intacto):\n", M)

M (intacto):
 [[1 2 3]
 [4 5 6]]


### 3.4 Máscaras booleanas (filtrado)

In [32]:
ventas = np.array([120, 600, 450, 800, 300, 900, 150])

mask = ventas > 500          # array de True/False
print("mask :", mask)
print("altas:", ventas[mask])

mask : [False  True False  True False  True False]
altas: [600 800 900]


In [33]:
# Combinar condiciones con & (and) y | (or) — paréntesis obligatorios
ventas[(ventas > 200) & (ventas < 700)]

array([600, 450, 300])

In [34]:
# Modificar valores con máscara
data = np.array([10, -5, 20, -1, 30])
data[data < 0] = 0   # negativos → 0
print(data)

[10  0 20  0 30]


In [35]:
# Máscara en 2D → resultado siempre es 1D aplanado
M = np.array([[10, -5, 20], [-1, 30, -10], [5, 15, -2]])
print(M[M > 0])

[10 20 30  5 15]


### 3.5 np.where (if-else vectorizado)

In [36]:
# 3 argumentos: where(condición, valor_si_true, valor_si_false)
presiones = np.array([95, 105, 110, 80, 120, 99])
estados = np.where(presiones > 100, "ALERTA", "NORMAL")
print(estados)

['NORMAL' 'ALERTA' 'ALERTA' 'NORMAL' 'ALERTA' 'NORMAL']


In [37]:
# 1 argumento: devuelve los ÍNDICES que cumplen la condición
arr = np.array([10, -5, 20, -1, 30])
indices = np.where(arr > 10)
print("índices:", indices)
print("valores:", arr[indices])

índices: (array([2, 4]),)
valores: [20 30]


---
## 4. Tratamiento de Datos

### 4.1 Agregaciones globales

In [38]:
X = np.array([[1, 2, 3], [4, 5, 6]])

print("sum  :", X.sum())
print("mean :", X.mean())
print("std  :", X.std())
print("min  :", X.min())
print("max  :", X.max())

sum  : 21
mean : 3.5
std  : 1.707825127659933
min  : 1
max  : 6


### 4.2 Agregaciones por eje
- `axis=0` → opera por columna (resultado: una fila)
- `axis=1` → opera por fila (resultado: una columna)

In [39]:
X = np.array([[1, 2, 3], [4, 5, 6]])

print("suma por columna (axis=0):", X.sum(axis=0))   # [5, 7, 9]
print("suma por fila    (axis=1):", X.sum(axis=1))   # [6, 15]

suma por columna (axis=0): [5 7 9]
suma por fila    (axis=1): [ 6 15]


In [40]:
# Promedio por columna (estadística por feature)
print("media por columna:", X.mean(axis=0))
print("media por fila   :", X.mean(axis=1))

media por columna: [2.5 3.5 4.5]
media por fila   : [2. 5.]


### 4.3 Acumulativas (evolución paso a paso)

In [41]:
arr = np.array([1, 2, 3, 4])
print("cumsum :", np.cumsum(arr))    # [1, 3, 6, 10]
print("cumprod:", np.cumprod(arr))   # [1, 2, 6, 24]

cumsum : [ 1  3  6 10]
cumprod: [ 1  2  6 24]


### 4.4 Manejo de NaN (valores faltantes)

In [42]:
# NaN se propaga: cualquier operación con NaN da NaN
datos = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
print("mean normal:", datos.mean())   # nan

mean normal: nan


In [43]:
# Detectar NaN
print("hay NaN?:", np.isnan(datos))
print("cantidad:", np.isnan(datos).sum())

hay NaN?: [False False  True False False]
cantidad: 1


In [44]:
# Funciones que IGNORAN los NaN
print("nanmean:", np.nanmean(datos))
print("nansum :", np.nansum(datos))
print("nanstd :", np.nanstd(datos))

nanmean: 3.0
nansum : 12.0
nanstd : 1.5811388300841898


In [45]:
# Reemplazar NaN por un valor (ej: la media)
datos_limpios = np.where(np.isnan(datos), np.nanmean(datos), datos)
print(datos_limpios)

[1. 2. 3. 4. 5.]


### 4.5 Normalización Min-Max (escala 0 a 1)

In [46]:
datos = np.array([10, 20, 30, 40, 50])
norm = (datos - datos.min()) / (datos.max() - datos.min())
print(norm)   # [0., 0.25, 0.5, 0.75, 1.]

[0.   0.25 0.5  0.75 1.  ]


### 4.6 Estandarización Z-Score (media 0, desvío 1)

In [47]:
datos = np.array([10, 20, 30, 40, 50])
z = (datos - datos.mean()) / datos.std()
print(z)
print("media:", z.mean().round(5), "| std:", z.std().round(5))

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
media: 0.0 | std: 1.0


In [48]:
# Z-Score por columna (broadcasting): cada feature en su propia escala
X = np.array([[1.0, 100.0], [2.0, 200.0], [3.0, 300.0], [4.0, 400.0]])
X_std = (X - X.mean(axis=0)) / X.std(axis=0)
print(X_std)

[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
