
# TP - Computación Científica con NumPy (Parte I)

## Objetivos
- Comprender la estructura y eficiencia del objeto ndarray.

- Dominar la manipulación de dimensiones y el cambio de forma (reshape).

- Aplicar técnicas de slicing y acceso indexado en múltiples dimensiones.


## Ejercicio 1 - Creación de arrays

1. Anatomía de un Array
Consigna: La base de NumPy es el ndarray. En este ejercicio exploraremos cómo se construyen y qué propiedades los definen.

1. Crea un array de una dimensión (1D) con 10 elementos aleatorios.
2. Crea una matriz de 3x3 (2D) rellena con ceros.
3. Utiliza los atributos de NumPy para imprimir en pantalla:
    *   La forma (shape).
    *   El tipo de datos (dtype).
    *   El número de dimensiones (ndim).
    *   La cantidad total de elementos (size).
4. Convierte el array de ceros (que por defecto es float64) a tipo de dato entero (int32).

In [10]:
import numpy as np

# 1. Array 1D con 10 elementos aleatorios
array_1d = np.random.rand(10)
print("Array 1D aleatorio:")
print(array_1d)

# 2. Matriz 3x3 rellena con ceros
matriz_ceros = np.zeros((3, 3))
print("\nMatriz 3x3 de ceros:")
print(matriz_ceros)

# 3. Atributos de la matriz de ceros
print("\n--- Atributos de la matriz de ceros ---")
print(f"Forma (shape):        {matriz_ceros.shape}")
print(f"Tipo de datos (dtype): {matriz_ceros.dtype}")
print(f"Dimensiones (ndim):    {matriz_ceros.ndim}")
print(f"Cantidad de elementos (size): {matriz_ceros.size}")

# 4. Convertir a int32
matriz_int = matriz_ceros.astype(np.int32)
print("\nMatriz convertida a int32:")
print(matriz_int)
print(f"Nuevo dtype: {matriz_int.dtype}")

Array 1D aleatorio:
[0.44255818 0.04342516 0.02219353 0.24596185 0.35245132 0.65355564
 0.77058456 0.01454207 0.04052527 0.54182309]

Matriz 3x3 de ceros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

--- Atributos de la matriz de ceros ---
Forma (shape):        (3, 3)
Tipo de datos (dtype): float64
Dimensiones (ndim):    2
Cantidad de elementos (size): 9

Matriz convertida a int32:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Nuevo dtype: int32



## Ejercicio 2 - Eficiencia y Gestión de Memoria

**Consigna**: NumPy es preferido sobre las listas de Python por su velocidad y bajo consumo de memoria. Vamos a comprobarlo empíricamente.

    1. Crea una lista de Python con 1.000.000 de números enteros.
    2. Crea un array de NumPy con los mismos 1.000.000 de elementos.
    3. Calcula y compara el espacio en memoria (en bytes) que ocupa cada estructura.
      Pista: Usa sys.getsizeof() para la lista y el atributo .nbytes para el array.
    4. Redacta una breve conclusión: ¿Cuántas veces más eficiente es NumPy en este caso?

In [ ]:
# Tu código aquí


## Ejercicio 3 - Selección Avanzada (Slicing e Indexado)

**Consigna**: Extraer información específica es una habilidad crítica. Trabajaremos sobre una matriz de 5x5.

    1. Genera una matriz de 5x5 con números del 1 al 25.
    2. Extrae la tercera fila completa.
    3. Extrae las dos últimas columnas.
    4. Extrae la submatriz central de 3x3 (excluyendo los bordes de la matriz original).
    5. Invierte el orden de las filas de la matriz (la primera pasa a ser la última).


In [ ]:
# Tu código aquí


## Ejercicio 4 - ventas_altas
Dado un array de ventas mensuales, queremos identificar los meses "exitosos" (ventas > 500) y obtener esos valores específicos.
ventas = np.array([120, 600, 450, 800, 300, 900, 150])

1. Crea una máscara booleana llamada 'mask' para ventas mayores a 500
mask = # Tu código aquí

2. Aplica la máscara al array original para obtener 'ventas_altas'
ventas_altas = # Tu código aquí

print(f"Máscara: {mask}")
print(f"Ventas filtradas: {ventas_altas}")

In [ ]:
# Tu código aquí

## Ejercicio 5 - Estados
Tienes un sensor que mide la presión. Si la presión es mayor a 100, márcala como "ALERTA". Si es menor o igual, márcala como "NORMAL".

presiones = np.array([95, 105, 110, 80, 120, 99])

1- Crea un array 'estados' usando np.where
estados = # Tu código aquí

print(f"Presiones: {presiones}")

print(f"Estados: {estados}")


In [ ]:
# Tu código aquí