
# TP - Computación Científica con NumPy (Parte I)

## Objetivos
- Comprender la estructura y eficiencia del objeto ndarray.

- Dominar la manipulación de dimensiones y el cambio de forma (reshape).

- Aplicar técnicas de slicing y acceso indexado en múltiples dimensiones.


## Ejercicio 1 - Creación de arrays

1. Anatomía de un Array
Consigna: La base de NumPy es el ndarray. En este ejercicio exploraremos cómo se construyen y qué propiedades los definen.

1. Crea un array de una dimensión (1D) con 10 elementos aleatorios.
2. Crea una matriz de 3x3 (2D) rellena con ceros.
3. Utiliza los atributos de NumPy para imprimir en pantalla:
    *   La forma (shape).
    *   El tipo de datos (dtype).
    *   El número de dimensiones (ndim).
    *   La cantidad total de elementos (size).
4. Convierte el array de ceros (que por defecto es float64) a tipo de dato entero (int32).

In [7]:
import numpy as np
#Si entro al cuadro de texto me salen solo 4 preguntas, respeto esa vista para la resolucion

# 1. Array 1D con 10 elementos aleatorios
array_1d = np.random.rand(10)
print("Array 1D aleatorio:")
print(array_1d)

# 2. Matriz 3x3 rellena con ceros
matriz_ceros = np.zeros((3, 3))
print("\nMatriz 3x3 de ceros:")
print(matriz_ceros)

# 3. Atributos de la matriz de ceros
print("\n--- Atributos de la matriz de ceros ---")
print(f"Forma (shape):        {matriz_ceros.shape}")
print(f"Tipo de datos (dtype): {matriz_ceros.dtype}")
print(f"Dimensiones (ndim):    {matriz_ceros.ndim}")
print(f"Cantidad de elementos (size): {matriz_ceros.size}")

# 4. Convertir a int32
matriz_int = matriz_ceros.astype(np.int32)
print("\nMatriz convertida a int32:")
print(matriz_int)
print(f"Nuevo dtype: {matriz_int.dtype}")

Array 1D aleatorio:
[0.65333343 0.97101425 0.15581979 0.38097429 0.67492132 0.80985806
 0.31957282 0.69979944 0.94520854 0.35001929]

Matriz 3x3 de ceros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

--- Atributos de la matriz de ceros ---
Forma (shape):        (3, 3)
Tipo de datos (dtype): float64
Dimensiones (ndim):    2
Cantidad de elementos (size): 9

Matriz convertida a int32:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Nuevo dtype: int32



## Ejercicio 2 - Eficiencia y Gestión de Memoria

**Consigna**: NumPy es preferido sobre las listas de Python por su velocidad y bajo consumo de memoria. Vamos a comprobarlo empíricamente.

    1. Crea una lista de Python con 1.000.000 de números enteros.
    2. Crea un array de NumPy con los mismos 1.000.000 de elementos.
    3. Calcula y compara el espacio en memoria (en bytes) que ocupa cada estructura.
      Pista: Usa sys.getsizeof() para la lista y el atributo .nbytes para el array.
    4. Redacta una breve conclusión: ¿Cuántas veces más eficiente es NumPy en este caso?

In [8]:
import numpy as np
import sys

# 1. Lista de Python con 1.000.000 de enteros
lista_python = list(range(1_000_000))

# 2. Array de NumPy con los mismos elementos
array_numpy = np.arange(1_000_000)

# 3. Comparación de memoria
# Para la lista: getsizeof devuelve solo el contenedor; sumamos los enteros
memoria_lista = sys.getsizeof(lista_python) + sum(sys.getsizeof(x) for x in lista_python)
memoria_array = array_numpy.nbytes

print(f"Memoria lista de Python: {memoria_lista:,} bytes ({memoria_lista/1024/1024:.2f} MB)")
print(f"Memoria array NumPy:     {memoria_array:,} bytes ({memoria_array/1024/1024:.2f} MB)")

# 4. Conclusión
veces_mas_eficiente = memoria_lista / memoria_array
print(f"\nNumPy es aproximadamente {veces_mas_eficiente:.1f} veces más eficiente en memoria.")
print("Esto se debe a que NumPy almacena los datos en un bloque contiguo de memoria")
print("con un tipo de dato fijo (int64 = 8 bytes por elemento), mientras que Python")
print("guarda cada entero como un objeto completo con metadatos (~28 bytes c/u).")
print("NumPy es más eficiente porque no desperdicia casilleros en metadatos y mantiene todo ordenado.")

Memoria lista de Python: 36,000,056 bytes (34.33 MB)
Memoria array NumPy:     8,000,000 bytes (7.63 MB)

NumPy es aproximadamente 4.5 veces más eficiente en memoria.
Esto se debe a que NumPy almacena los datos en un bloque contiguo de memoria
con un tipo de dato fijo (int64 = 8 bytes por elemento), mientras que Python
guarda cada entero como un objeto completo con metadatos (~28 bytes c/u).
NumPy es más eficiente porque no desperdicia casilleros en metadatos y mantiene todo ordenado.



## Ejercicio 3 - Selección Avanzada (Slicing e Indexado)

**Consigna**: Extraer información específica es una habilidad crítica. Trabajaremos sobre una matriz de 5x5.

    1. Genera una matriz de 5x5 con números del 1 al 25.
    2. Extrae la tercera fila completa.
    3. Extrae las dos últimas columnas.
    4. Extrae la submatriz central de 3x3 (excluyendo los bordes de la matriz original).
    5. Invierte el orden de las filas de la matriz (la primera pasa a ser la última).


In [9]:
import numpy as np

# 1. Matriz 5x5 con números del 1 al 25
matriz = np.arange(1, 26).reshape(5, 5)
print("Matriz original 5x5:")
print(matriz)

# 2. Tercera fila completa (índice 2)
tercera_fila = matriz[2, :]
print(f"\nTercera fila: {tercera_fila}")
tercera_fila_2 = matriz[2]
print(f"Tercera fila (otra forma): {tercera_fila_2}")

# 3. Dos últimas columnas
ultimas_columnas = matriz[:, -2:]
print("\nDos últimas columnas:")
print(ultimas_columnas)


# 4. Submatriz central de 3x3 (excluyendo bordes)
submatriz_central = matriz[1:4, 1:4]
print("\nSubmatriz central 3x3:")
print(submatriz_central)

# 5. Invertir el orden de las filas
matriz_invertida = matriz[::-1]
print("\nMatriz con filas invertidas:")
print(matriz_invertida)

Matriz original 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Tercera fila: [11 12 13 14 15]
Tercera fila (otra forma): [11 12 13 14 15]

Dos últimas columnas:
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]

Submatriz central 3x3:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Matriz con filas invertidas:
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]



## Ejercicio 4 - ventas_altas
Dado un array de ventas mensuales, queremos identificar los meses "exitosos" (ventas > 500) y obtener esos valores específicos.
ventas = np.array([120, 600, 450, 800, 300, 900, 150])

1. Crea una máscara booleana llamada 'mask' para ventas mayores a 500
mask = ventas > 500

2. Aplica la máscara al array original para obtener 'ventas_altas'
ventas_altas = ventas[mask]

print(f"Máscara: {mask}")
print(f"Ventas filtradas: {ventas_altas}")

In [10]:
import numpy as np

ventas = np.array([120, 600, 450, 800, 300, 900, 150])

# 1. Máscara booleana para ventas > 500
mask = ventas > 500

# 2. Aplicar la máscara
ventas_altas = ventas[mask]

print(f"Ventas originales: {ventas}")
print(f"Máscara: {mask}")
print(f"Ventas filtradas (> 500): {ventas_altas}")

Ventas originales: [120 600 450 800 300 900 150]
Máscara: [False  True False  True False  True False]
Ventas filtradas (> 500): [600 800 900]


## Ejercicio 5 - Estados
Tienes un sensor que mide la presión. Si la presión es mayor a 100, márcala como "ALERTA". Si es menor o igual, márcala como "NORMAL".

presiones = np.array([95, 105, 110, 80, 120, 99])

1- Crea un array 'estados' usando np.where
estados = np.where(presiones > 100, "ALERTA", "NORMAL")

print(f"Presiones: {presiones}")

print(f"Estados: {estados}")


In [11]:
import numpy as np

presiones = np.array([95, 105, 110, 80, 120, 99])

# Crear array 'estados' usando np.where
estados = np.where(presiones > 100, "ALERTA", "NORMAL")

print(f"Presiones: {presiones}")
print(f"Estados:   {estados}")

Presiones: [ 95 105 110  80 120  99]
Estados:   ['NORMAL' 'ALERTA' 'ALERTA' 'NORMAL' 'ALERTA' 'NORMAL']
